{ config, pkgs, host, ... }:
let
  # The Bedrock API key lives in the login Keychain, never in this repo or
  # the nix store. Store it with `claude-bedrock-set-key`.
  keychainService = "claude-bedrock";
  bedrockRegion = "us-east-1";

  # Same `claude`, pointed at Bedrock instead of the claude.ai subscription.
  claude-bedrock = pkgs.writeShellScriptBin "claude-bedrock" ''
    if ! token=$(/usr/bin/security find-generic-password -a "$USER" -s ${keychainService} -w 2>/dev/null); then
      echo "claude-bedrock: no key in Keychain; run claude-bedrock-set-key first" >&2
      exit 1
    fi
    export CLAUDE_CODE_USE_BEDROCK=1
    export AWS_REGION="''${AWS_REGION:-${bedrockRegion}}"
    export AWS_BEARER_TOKEN_BEDROCK="$token"
    exec ${pkgs.claude-code}/bin/claude "$@"
  '';

  claude-bedrock-set-key = pkgs.writeShellScriptBin "claude-bedrock-set-key" ''
    # Prompts for the key (no echo) and creates or updates the Keychain item.
    # Read here rather than by `security -w`, whose own prompt silently cuts
    # input off at 128 characters -- shorter than a Bedrock API key.
    read -rs -p "Bedrock API key: " key
    echo
    key=''${key//[[:space:]]/}
    [ -n "$key" ] || { echo "claude-bedrock-set-key: no key given" >&2; exit 1; }
    /usr/bin/security add-generic-password -U -a "$USER" -s ${keychainService} -w "$key"
    echo "Stored (''${#key} characters)."
  '';

  # Stores the Jira API token where jira-cli looks for it: a Keychain item
  # with service "jira-cli" and the Jira login as the account.
  jira-set-token = pkgs.writeShellScriptBin "jira-set-token" ''
    config=''${JIRA_CONFIG_FILE:-$HOME/.config/.jira/.config.yml}
    login=$(sed -n 's/^login: *//p' "$config" 2>/dev/null)
    [ -n "$login" ] || read -r -p "Jira login email: " login
    read -rs -p "Jira API token for $login: " token
    echo
    token=''${token//[[:space:]]/}
    [ -n "$token" ] || { echo "jira-set-token: no token given" >&2; exit 1; }
    /usr/bin/security add-generic-password -U -s jira-cli -a "$login" -w "$token"
    echo "Stored (''${#token} characters) for $login."
  '';

  # Rebuilds from the private flake that describes this machine, using the
  # local checkout of this repo instead of the revision pinned there.
  rebuild = pkgs.writeShellScriptBin "rebuild" ''
    exec sudo darwin-rebuild switch --flake ${host.privateDir} \
      --override-input dotfiles ${host.dotfilesDir} "$@"
  '';

  agent-backends-bedrock-el = pkgs.writeText "agent-backends-bedrock.el" ''
    ;;; agent-backends-bedrock.el --- Claude via Bedrock (generated by nix) -*- lexical-binding: t; -*-

    (defun agent-backends--bedrock-token ()
      "Return the Bedrock API key from the login Keychain."
      (with-temp-buffer
        (unless (zerop (call-process "/usr/bin/security" nil t nil
                                     "find-generic-password"
                                     "-a" (user-login-name)
                                     "-s" "${keychainService}" "-w"))
          (user-error "No Bedrock key in Keychain; run claude-bedrock-set-key"))
        (string-trim (buffer-string))))

    (defvar agent-shell-anthropic-claude-environment)

    (defun agent-backends--environment (backend)
      "Return the agent-shell Claude environment for BACKEND.
    BACKEND is the symbol `subscription' or `bedrock'."
      (pcase backend
        ('bedrock
         (agent-shell-make-environment-variables
          "CLAUDE_CODE_USE_BEDROCK" "1"
          "AWS_REGION" "${bedrockRegion}"
          "AWS_BEARER_TOKEN_BEDROCK" (agent-backends--bedrock-token)
          :inherit-env t))
        ('subscription nil)
        (_ (user-error "Unknown backend: %s" backend))))

    (defun agent-backends-claude (backend)
      "Make new agent-shell Claude sessions use BACKEND by default.
    BACKEND is the symbol `subscription' or `bedrock'.  Sessions started
    with `agent-shell-claude-bedrock' or `agent-shell-claude-subscription'
    ignore this."
      (interactive
       (list (intern (completing-read "Claude backend: "
                                      '("subscription" "bedrock") nil t))))
      (setq agent-shell-anthropic-claude-environment
            (agent-backends--environment backend))
      (message "agent-shell Claude backend: %s" backend))

    (defun agent-backends--start (backend name)
      "Start a Claude session on BACKEND, in a buffer named after NAME."
      (require 'agent-shell)
      (let ((environment (agent-backends--environment backend))
            (config (copy-alist (agent-shell-anthropic-make-claude-code-config))))
        (setf (alist-get :buffer-name config) name
              (alist-get :mode-line-name config) name
              (alist-get :client-maker config)
              (lambda (buffer)
                (let ((agent-shell-anthropic-claude-environment environment))
                  (agent-shell-anthropic-make-claude-client :buffer buffer))))
        (agent-shell-start :config config)))

    (defun agent-shell-claude-bedrock ()
      "Start a Claude session that uses Bedrock, whatever the default is."
      (interactive)
      (agent-backends--start 'bedrock "Claude Bedrock"))

    (defun agent-shell-claude-subscription ()
      "Start a Claude session that uses the subscription, whatever the default is."
      (interactive)
      (agent-backends--start 'subscription "Claude Subscription"))

    (provide 'agent-backends-bedrock)
    ;;; agent-backends-bedrock.el ends here
  '';
in
{
  home.packages = [
    # GNU ls as `gls`, for dired (insert-directory-program in init.el).
    pkgs.coreutils-prefixed
    claude-bedrock
    claude-bedrock-set-key
    jira-set-token
    rebuild
  ];

  # Loaded by agent-backends.el.
  home.file.".emacs.d/lisp/agent-backends-bedrock.el".source = agent-backends-bedrock-el;

  home.file.".bashrc.darwin".source =
    config.lib.file.mkOutOfStoreSymlink "${host.dotfilesDir}/.bashrc.darwin";

  # pinentry-mac asks for key passphrases in a dialog (and can save them in
  # the Keychain), so signing works from Emacs, where there is no terminal.
  services.gpg-agent = {
    enable = true;
    pinentry.package = pkgs.pinentry_mac;
  };
}
