{ config, pkgs, host, ... }:
let
  # The Bedrock API key lives in the login Keychain, never in this repo or
  # the nix store. Store it with `claude-bedrock-set-key`.
  keychainService = "claude-bedrock";
  bedrockRegion = "us-east-1";

  # Same `claude`, pointed at Bedrock instead of the claude.ai subscription.
  claude-bedrock = pkgs.writeShellScriptBin "claude-bedrock" ''
    if ! token=$(/usr/bin/security find-generic-password -a "$USER" -s ${keychainService} -w 2>/dev/null); then
      echo "claude-bedrock: no key in Keychain; run claude-bedrock-set-key first" >&2
      exit 1
    fi
    export CLAUDE_CODE_USE_BEDROCK=1
    export AWS_REGION="''${AWS_REGION:-${bedrockRegion}}"
    export AWS_BEARER_TOKEN_BEDROCK="$token"
    exec ${pkgs.claude-code}/bin/claude "$@"
  '';

  claude-bedrock-set-key = pkgs.writeShellScriptBin "claude-bedrock-set-key" ''
    # Prompts for the key (no echo) and creates or updates the Keychain item.
    # Read here rather than by `security -w`, whose own prompt silently cuts
    # input off at 128 characters -- shorter than a Bedrock API key.
    read -rs -p "Bedrock API key: " key
    echo
    key=''${key//[[:space:]]/}
    [ -n "$key" ] || { echo "claude-bedrock-set-key: no key given" >&2; exit 1; }
    /usr/bin/security add-generic-password -U -a "$USER" -s ${keychainService} -w "$key"
    echo "Stored (''${#key} characters)."
  '';

  # Rebuilds from the private flake that describes this machine, using the
  # local checkout of this repo instead of the revision pinned there.
  rebuild = pkgs.writeShellScriptBin "rebuild" ''
    exec sudo darwin-rebuild switch --flake ${host.privateDir} \
      --override-input dotfiles ${host.dotfilesDir} "$@"
  '';

  agent-backends-bedrock-el = pkgs.writeText "agent-backends-bedrock.el" ''
    ;;; agent-backends-bedrock.el --- Claude via Bedrock (generated by nix) -*- lexical-binding: t; -*-

    (defun agent-backends--bedrock-token ()
      "Return the Bedrock API key from the login Keychain."
      (with-temp-buffer
        (unless (zerop (call-process "/usr/bin/security" nil t nil
                                     "find-generic-password"
                                     "-a" (user-login-name)
                                     "-s" "${keychainService}" "-w"))
          (user-error "No Bedrock key in Keychain; run claude-bedrock-set-key"))
        (string-trim (buffer-string))))

    (defun agent-backends-claude (backend)
      "Make new agent-shell Claude sessions use BACKEND.
    BACKEND is the symbol `subscription' or `bedrock'."
      (interactive
       (list (intern (completing-read "Claude backend: "
                                      '("subscription" "bedrock") nil t))))
      (setq agent-shell-anthropic-claude-environment
            (pcase backend
              ('bedrock
               (agent-shell-make-environment-variables
                "CLAUDE_CODE_USE_BEDROCK" "1"
                "AWS_REGION" "${bedrockRegion}"
                "AWS_BEARER_TOKEN_BEDROCK" (agent-backends--bedrock-token)
                :inherit-env t))
              ('subscription nil)
              (_ (user-error "Unknown backend: %s" backend))))
      (message "agent-shell Claude backend: %s" backend))

    (provide 'agent-backends-bedrock)
    ;;; agent-backends-bedrock.el ends here
  '';
in
{
  home.packages = [
    # GNU ls as `gls`, for dired (insert-directory-program in init.el).
    pkgs.coreutils-prefixed
    claude-bedrock
    claude-bedrock-set-key
    rebuild
  ];

  # Loaded by agent-backends.el.
  home.file.".emacs.d/lisp/agent-backends-bedrock.el".source = agent-backends-bedrock-el;

  home.file.".bashrc.darwin".source =
    config.lib.file.mkOutOfStoreSymlink "${host.dotfilesDir}/.bashrc.darwin";

  # pinentry-mac asks for key passphrases in a dialog (and can save them in
  # the Keychain), so signing works from Emacs, where there is no terminal.
  services.gpg-agent = {
    enable = true;
    pinentry.package = pkgs.pinentry_mac;
  };
}
