{ config, pkgs, lib, inputs, host, ... }:
let
  # Config files are linked to the checkout rather than copied into the
  # store, so edits take effect without a rebuild.
  link = path: config.lib.file.mkOutOfStoreSymlink "${host.dotfilesDir}/${path}";
  emacsLink = path: link ".emacs.d/${path}";

  # Prebuilt grammars for the languages init.el asks treesit-auto for, so
  # Emacs doesn't offer to clone and compile them on first start.
  treesit-grammars = pkgs.emacsPackages.treesit-grammars.with-grammars (g: [
    g.tree-sitter-go
    g.tree-sitter-gomod
    g.tree-sitter-javascript
    g.tree-sitter-nix
    g.tree-sitter-templ
  ]);

  # Emacs is not always started from a shell (on macOS, the Dock), so the
  # agent binaries are referenced by store path rather than found on PATH.
  agent-backends-el = pkgs.writeText "agent-backends.el" ''
    ;;; agent-backends.el --- agent-shell backends (generated by nix) -*- lexical-binding: t; -*-

    (with-eval-after-load 'agent-shell
      (setq agent-shell-anthropic-claude-acp-command
            '("${pkgs.claude-agent-acp}/bin/claude-agent-acp")
            agent-shell-openai-codex-acp-command
            '("${pkgs.codex-acp}/bin/codex-acp")))

    ;; The Bedrock switch needs somewhere to keep the API key, which is
    ;; platform-specific, so it is only generated where one is set up.
    (load (expand-file-name "lisp/agent-backends-bedrock" user-emacs-directory)
          :noerror)

    (provide 'agent-backends)
    ;;; agent-backends.el ends here
  '';
in
{
  home.stateVersion = "26.05";

  home.packages = [
    pkgs.gh
    pkgs.gawk
    pkgs.ripgrep
    pkgs.nixpkgs-fmt
    pkgs.tmux
    # Markdown rendering for crafted-writing-config.
    pkgs.pandoc
    # Go tooling used by ftlio-golang-config.el (eglot, flycheck, templ).
    pkgs.go
    pkgs.gopls
    pkgs.golangci-lint
    pkgs.templ
    # `jira`. Reads its API token from the system keyring (on macOS, the
    # Keychain; see jira-set-token), so it works from scripts and agents too.
    pkgs.jira-cli-go
    # Reading .xlsx files (e.g. the security risk register) from scripts.
    (pkgs.python3.withPackages (ps: [ ps.openpyxl ]))
    pkgs.claude-code
    pkgs.codex
    pkgs.claude-agent-acp
    pkgs.codex-acp
  ];

  # Loaded by ftlio-ai-config.el.
  home.file.".emacs.d/lisp/agent-backends.el".source = agent-backends-el;
  # Per-machine Emacs settings from the host description; loaded by init.el.
  home.file.".emacs.d/lisp/host-local.el".text = ''
    ;;; host-local.el --- per-machine settings (generated by nix) -*- lexical-binding: t; -*-

    ${host.emacsExtra}
    ;;; host-local.el ends here
  '';

  home.file.".emacs.d/early-init.el".source = emacsLink "early-init.el";
  home.file.".emacs.d/init.el".source = emacsLink "init.el";
  home.file.".emacs.d/ftlio".source = emacsLink "ftlio";
  home.file.".emacs.d/other-packages".source = emacsLink "other-packages";
  home.file.".config/crafted-emacs".source = inputs.crafted-emacs;
  # Linked file by file, so grammars Emacs installs itself can sit alongside.
  home.file.".emacs.d/tree-sitter" = {
    source = "${treesit-grammars}/lib";
    recursive = true;
  };

  home.file.".tmux.conf".source = link ".tmux.conf";

  # .bashrc is plain bash; nix only puts what it sources where it looks.
  # It picks up a platform file (.bashrc.darwin, from home-darwin.nix) itself.
  home.file.".bashrc".source = link ".bashrc";
  home.file.".bash_profile".source = link ".bash_profile";
  home.file.".oh-my-bash".source = inputs.oh-my-bash;
  home.file.".local/share/blesh".source = "${pkgs.blesh}/share/blesh";

  programs.git = {
    enable = true;
    ignores = [
      # Emacs
      "*~"
      "\\#*\\#"
      "/.emacs.desktop"
      "/.emacs.desktop.lock"
      ".tern-*"
      ".\\#*"
      ".projectile"
      # OS Files
      ".DS_Store"
      ".DS_Store?"
      ".Spotlight-V100"
      ".Trashes"
      ".ehthumbs.db"
      "Thumbs.db"
      # Coding agents: instructions, local settings and scratch state.
      # Ignored everywhere by default; a repo that shares them tracks them
      # with `git add -f`, after which this no longer applies to them.
      "CLAUDE.md"
      "CLAUDE.local.md"
      ".claude/"
      "AGENTS.md"
      "AGENTS.override.md"
      ".codex/"
    ];
    settings = {
      user = {
        inherit (host.git) name email;
      } // lib.optionalAttrs (host.git.signingKey != null) {
        inherit (host.git) signingKey;
      };
      commit.gpgSign = host.git.signingKey != null;
      tag.gpgSign = host.git.signingKey != null;
      core.editor = "emacs";
      url."git@github.com:".insteadOf = [ "https://github.com" "https://github.com/" ];
    };
    # Other identities, each applying to the repos under one directory.
    includes = map
      (identity: {
        condition = "gitdir:${identity.gitdir}";
        contents.user = removeAttrs identity [ "gitdir" ];
      })
      host.git.identities;
  };

  programs.gpg.enable = true;

  # The shell hook is in .bashrc.
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  # Two keys: github_ftlio for GitHub only, id_ed25519 for everything else
  # (servers, other machines). IdentitiesOnly keeps ssh from offering a host
  # every key in the agent.
  #
  # On macOS, key passphrases come from the login Keychain. Store each once
  # with:
  #   ssh-add --apple-use-keychain ~/.ssh/<key>
  # UseKeychain is an Apple extension; IgnoreUnknown lets any other ssh skip
  # it.
  home.file.".ssh/config".text = ''
    ${host.sshConfig}
    Host github.com
      IdentityFile ~/.ssh/github_ftlio

    Host *
      IgnoreUnknown UseKeychain
      UseKeychain yes
      AddKeysToAgent yes
      IdentitiesOnly yes
      IdentityFile ~/.ssh/id_ed25519
  '';
}
